name: Update Beta File Count
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: 
      - main

jobs:
   betapro-file-count:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
       python-version: 3.8
    - name: Execute py script
      run: |
         cd Betaprograming
         pip install PyGithub==1.54.1 && 
         python beta-count.py
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}