name : Update-profile-count

on : 
  push:
    branches:
      - master 

jobs:
  Update-profile-count:
    name : Update-profile-count
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v2 
      - uses : actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Exevute py script
        run: |
          pip install PyGithub && python main.py
        env:
          ACCESS_TOKEN: ${{secrets.GH_TOKEN}}
